// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kindling_grpc.proto

package model

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RpcAttType int32

const (
	RpcAttType_STRING RpcAttType = 0
	RpcAttType_INT    RpcAttType = 1
	RpcAttType_BOOL   RpcAttType = 2
)

var RpcAttType_name = map[int32]string{
	0: "STRING",
	1: "INT",
	2: "BOOL",
}

var RpcAttType_value = map[string]int32{
	"STRING": 0,
	"INT":    1,
	"BOOL":   2,
}

func (x RpcAttType) String() string {
	return proto.EnumName(RpcAttType_name, int32(x))
}

func (RpcAttType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7ce63d8b968de3eb, []int{0}
}

type PodInfos struct {
	HostIp               string     `protobuf:"bytes,1,opt,name=host_ip,json=hostIp,proto3" json:"host_ip,omitempty"`
	Timestamp            uint64     `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Pods                 []*PodInfo `protobuf:"bytes,3,rep,name=pods,proto3" json:"pods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PodInfos) Reset()         { *m = PodInfos{} }
func (m *PodInfos) String() string { return proto.CompactTextString(m) }
func (*PodInfos) ProtoMessage()    {}
func (*PodInfos) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ce63d8b968de3eb, []int{0}
}
func (m *PodInfos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodInfos.Unmarshal(m, b)
}
func (m *PodInfos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodInfos.Marshal(b, m, deterministic)
}
func (m *PodInfos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodInfos.Merge(m, src)
}
func (m *PodInfos) XXX_Size() int {
	return xxx_messageInfo_PodInfos.Size(m)
}
func (m *PodInfos) XXX_DiscardUnknown() {
	xxx_messageInfo_PodInfos.DiscardUnknown(m)
}

var xxx_messageInfo_PodInfos proto.InternalMessageInfo

func (m *PodInfos) GetHostIp() string {
	if m != nil {
		return m.HostIp
	}
	return ""
}

func (m *PodInfos) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *PodInfos) GetPods() []*PodInfo {
	if m != nil {
		return m.Pods
	}
	return nil
}

type PodInfo struct {
	Sip                  uint32   `protobuf:"varint,1,opt,name=sip,proto3" json:"sip,omitempty"`
	Sport                uint32   `protobuf:"varint,2,opt,name=sport,proto3" json:"sport,omitempty"`
	Dport                uint32   `protobuf:"varint,3,opt,name=dport,proto3" json:"dport,omitempty"`
	UpdateTime           uint64   `protobuf:"varint,4,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodInfo) Reset()         { *m = PodInfo{} }
func (m *PodInfo) String() string { return proto.CompactTextString(m) }
func (*PodInfo) ProtoMessage()    {}
func (*PodInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ce63d8b968de3eb, []int{1}
}
func (m *PodInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodInfo.Unmarshal(m, b)
}
func (m *PodInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodInfo.Marshal(b, m, deterministic)
}
func (m *PodInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodInfo.Merge(m, src)
}
func (m *PodInfo) XXX_Size() int {
	return xxx_messageInfo_PodInfo.Size(m)
}
func (m *PodInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PodInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PodInfo proto.InternalMessageInfo

func (m *PodInfo) GetSip() uint32 {
	if m != nil {
		return m.Sip
	}
	return 0
}

func (m *PodInfo) GetSport() uint32 {
	if m != nil {
		return m.Sport
	}
	return 0
}

func (m *PodInfo) GetDport() uint32 {
	if m != nil {
		return m.Dport
	}
	return 0
}

func (m *PodInfo) GetUpdateTime() uint64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type PodReply struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodReply) Reset()         { *m = PodReply{} }
func (m *PodReply) String() string { return proto.CompactTextString(m) }
func (*PodReply) ProtoMessage()    {}
func (*PodReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ce63d8b968de3eb, []int{2}
}
func (m *PodReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodReply.Unmarshal(m, b)
}
func (m *PodReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodReply.Marshal(b, m, deterministic)
}
func (m *PodReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodReply.Merge(m, src)
}
func (m *PodReply) XXX_Size() int {
	return xxx_messageInfo_PodReply.Size(m)
}
func (m *PodReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PodReply.DiscardUnknown(m)
}

var xxx_messageInfo_PodReply proto.InternalMessageInfo

func (m *PodReply) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type RpcReply struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcReply) Reset()         { *m = RpcReply{} }
func (m *RpcReply) String() string { return proto.CompactTextString(m) }
func (*RpcReply) ProtoMessage()    {}
func (*RpcReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ce63d8b968de3eb, []int{3}
}
func (m *RpcReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcReply.Unmarshal(m, b)
}
func (m *RpcReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcReply.Marshal(b, m, deterministic)
}
func (m *RpcReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcReply.Merge(m, src)
}
func (m *RpcReply) XXX_Size() int {
	return xxx_messageInfo_RpcReply.Size(m)
}
func (m *RpcReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcReply.DiscardUnknown(m)
}

var xxx_messageInfo_RpcReply proto.InternalMessageInfo

func (m *RpcReply) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type RpcDatas struct {
	Datas                []*RpcData `protobuf:"bytes,1,rep,name=datas,proto3" json:"datas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RpcDatas) Reset()         { *m = RpcDatas{} }
func (m *RpcDatas) String() string { return proto.CompactTextString(m) }
func (*RpcDatas) ProtoMessage()    {}
func (*RpcDatas) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ce63d8b968de3eb, []int{4}
}
func (m *RpcDatas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcDatas.Unmarshal(m, b)
}
func (m *RpcDatas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcDatas.Marshal(b, m, deterministic)
}
func (m *RpcDatas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcDatas.Merge(m, src)
}
func (m *RpcDatas) XXX_Size() int {
	return xxx_messageInfo_RpcDatas.Size(m)
}
func (m *RpcDatas) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcDatas.DiscardUnknown(m)
}

var xxx_messageInfo_RpcDatas proto.InternalMessageInfo

func (m *RpcDatas) GetDatas() []*RpcData {
	if m != nil {
		return m.Datas
	}
	return nil
}

type RpcData struct {
	Sport                uint32     `protobuf:"varint,1,opt,name=sport,proto3" json:"sport,omitempty"`
	Dip                  string     `protobuf:"bytes,2,opt,name=dip,proto3" json:"dip,omitempty"`
	Dport                uint32     `protobuf:"varint,3,opt,name=dport,proto3" json:"dport,omitempty"`
	Timestamp            uint64     `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RpcId                int64      `protobuf:"varint,5,opt,name=rpc_id,json=rpcId,proto3" json:"rpc_id,omitempty"`
	Size_                int64      `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Attrs                []*RpcAttr `protobuf:"bytes,7,rep,name=attrs,proto3" json:"attrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RpcData) Reset()         { *m = RpcData{} }
func (m *RpcData) String() string { return proto.CompactTextString(m) }
func (*RpcData) ProtoMessage()    {}
func (*RpcData) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ce63d8b968de3eb, []int{5}
}
func (m *RpcData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcData.Unmarshal(m, b)
}
func (m *RpcData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcData.Marshal(b, m, deterministic)
}
func (m *RpcData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcData.Merge(m, src)
}
func (m *RpcData) XXX_Size() int {
	return xxx_messageInfo_RpcData.Size(m)
}
func (m *RpcData) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcData.DiscardUnknown(m)
}

var xxx_messageInfo_RpcData proto.InternalMessageInfo

func (m *RpcData) GetSport() uint32 {
	if m != nil {
		return m.Sport
	}
	return 0
}

func (m *RpcData) GetDip() string {
	if m != nil {
		return m.Dip
	}
	return ""
}

func (m *RpcData) GetDport() uint32 {
	if m != nil {
		return m.Dport
	}
	return 0
}

func (m *RpcData) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RpcData) GetRpcId() int64 {
	if m != nil {
		return m.RpcId
	}
	return 0
}

func (m *RpcData) GetSize_() int64 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *RpcData) GetAttrs() []*RpcAttr {
	if m != nil {
		return m.Attrs
	}
	return nil
}

type RpcAttr struct {
	Key                  string     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string     `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Type                 RpcAttType `protobuf:"varint,3,opt,name=type,proto3,enum=kindling.RpcAttType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RpcAttr) Reset()         { *m = RpcAttr{} }
func (m *RpcAttr) String() string { return proto.CompactTextString(m) }
func (*RpcAttr) ProtoMessage()    {}
func (*RpcAttr) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ce63d8b968de3eb, []int{6}
}
func (m *RpcAttr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcAttr.Unmarshal(m, b)
}
func (m *RpcAttr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcAttr.Marshal(b, m, deterministic)
}
func (m *RpcAttr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcAttr.Merge(m, src)
}
func (m *RpcAttr) XXX_Size() int {
	return xxx_messageInfo_RpcAttr.Size(m)
}
func (m *RpcAttr) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcAttr.DiscardUnknown(m)
}

var xxx_messageInfo_RpcAttr proto.InternalMessageInfo

func (m *RpcAttr) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RpcAttr) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *RpcAttr) GetType() RpcAttType {
	if m != nil {
		return m.Type
	}
	return RpcAttType_STRING
}

func init() {
	proto.RegisterEnum("kindling.RpcAttType", RpcAttType_name, RpcAttType_value)
	proto.RegisterType((*PodInfos)(nil), "kindling.PodInfos")
	proto.RegisterType((*PodInfo)(nil), "kindling.PodInfo")
	proto.RegisterType((*PodReply)(nil), "kindling.PodReply")
	proto.RegisterType((*RpcReply)(nil), "kindling.RpcReply")
	proto.RegisterType((*RpcDatas)(nil), "kindling.RpcDatas")
	proto.RegisterType((*RpcData)(nil), "kindling.RpcData")
	proto.RegisterType((*RpcAttr)(nil), "kindling.RpcAttr")
}

func init() { proto.RegisterFile("kindling_grpc.proto", fileDescriptor_7ce63d8b968de3eb) }

var fileDescriptor_7ce63d8b968de3eb = []byte{
	// 448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0x51, 0x8b, 0xd3, 0x40,
	0x10, 0xc7, 0x9b, 0x4b, 0x9a, 0xb4, 0x53, 0x2b, 0x71, 0x3c, 0x35, 0x88, 0x60, 0x09, 0x88, 0x41,
	0xa1, 0x42, 0xef, 0xc5, 0x57, 0x0f, 0xe1, 0x08, 0xc8, 0x9d, 0xec, 0xf5, 0x49, 0x1f, 0x4a, 0xcc,
	0xae, 0xd7, 0xe5, 0xd2, 0xee, 0xb2, 0xbb, 0x15, 0x7a, 0xdf, 0xcc, 0x6f, 0x27, 0xbb, 0x9b, 0x5c,
	0x6d, 0xab, 0xf7, 0x52, 0x66, 0x7e, 0x3b, 0x3b, 0xfd, 0xff, 0x67, 0x27, 0xf0, 0xf4, 0x96, 0xaf,
	0x69, 0xc3, 0xd7, 0x37, 0x8b, 0x1b, 0x25, 0xeb, 0xa9, 0x54, 0xc2, 0x08, 0x1c, 0x74, 0x30, 0x5f,
	0xc2, 0xe0, 0xab, 0xa0, 0xe5, 0xfa, 0xa7, 0xd0, 0xf8, 0x02, 0x92, 0xa5, 0xd0, 0x66, 0xc1, 0x65,
	0x16, 0x4c, 0x82, 0x62, 0x48, 0x62, 0x9b, 0x96, 0x12, 0x5f, 0xc1, 0xd0, 0xf0, 0x15, 0xd3, 0xa6,
	0x5a, 0xc9, 0xec, 0x64, 0x12, 0x14, 0x11, 0xd9, 0x01, 0x7c, 0x03, 0x91, 0x14, 0x54, 0x67, 0xe1,
	0x24, 0x2c, 0x46, 0xb3, 0x27, 0xd3, 0xae, 0xf7, 0xb4, 0x6d, 0x4c, 0xdc, 0x71, 0xbe, 0x84, 0xa4,
	0x05, 0x98, 0x42, 0xa8, 0xdb, 0x3f, 0x19, 0x13, 0x1b, 0xe2, 0x29, 0xf4, 0xb5, 0x14, 0xca, 0xb8,
	0xee, 0x63, 0xe2, 0x13, 0x4b, 0xa9, 0xa3, 0xa1, 0xa7, 0x2e, 0xc1, 0xd7, 0x30, 0xda, 0x48, 0x5a,
	0x19, 0xb6, 0xb0, 0x1a, 0xb2, 0xc8, 0xe9, 0x01, 0x8f, 0xe6, 0x7c, 0xc5, 0xf2, 0xdc, 0x79, 0x22,
	0x4c, 0x36, 0x5b, 0x7c, 0x0e, 0xb1, 0x62, 0x7a, 0xd3, 0x98, 0xce, 0x92, 0xcf, 0x6c, 0x0d, 0x91,
	0xf5, 0xc3, 0x35, 0x67, 0xae, 0xe6, 0x73, 0x65, 0x2a, 0x8d, 0x6f, 0xa1, 0x4f, 0x6d, 0x90, 0x05,
	0x87, 0x2e, 0xdb, 0x12, 0xe2, 0xcf, 0xf3, 0xdf, 0x01, 0x24, 0x2d, 0xda, 0xb9, 0x0a, 0xfe, 0x76,
	0x95, 0x42, 0x48, 0xb9, 0x9f, 0xe3, 0x90, 0xd8, 0xf0, 0x3f, 0x3e, 0xf7, 0xa6, 0x1e, 0x1d, 0x4e,
	0xfd, 0x19, 0xc4, 0x4a, 0xd6, 0x0b, 0x4e, 0xb3, 0xfe, 0x24, 0x28, 0x42, 0xd2, 0x57, 0xb2, 0x2e,
	0x29, 0x22, 0x44, 0x9a, 0xdf, 0xb1, 0x2c, 0x76, 0xd0, 0xc5, 0x56, 0x7b, 0x65, 0x8c, 0xd2, 0x59,
	0xf2, 0x0f, 0xed, 0x9f, 0x8c, 0x51, 0xc4, 0x9f, 0xe7, 0xdf, 0x9d, 0x74, 0x4b, 0xac, 0xc8, 0x5b,
	0xb6, 0x6d, 0x07, 0x62, 0x43, 0x2b, 0xf2, 0x57, 0xd5, 0x6c, 0x58, 0x2b, 0xdc, 0x27, 0x58, 0x40,
	0x64, 0xb6, 0x92, 0x39, 0xe5, 0x8f, 0x67, 0xa7, 0x87, 0xad, 0xe7, 0x5b, 0xc9, 0x88, 0xab, 0x78,
	0xf7, 0x1e, 0x60, 0xc7, 0x10, 0x20, 0xbe, 0x9e, 0x93, 0xf2, 0xf2, 0x22, 0xed, 0x61, 0x02, 0x61,
	0x79, 0x39, 0x4f, 0x03, 0x1c, 0x40, 0x74, 0x7e, 0x75, 0xf5, 0x25, 0x3d, 0x99, 0xdd, 0x41, 0x74,
	0xa1, 0x64, 0x8d, 0x1f, 0xe1, 0xd1, 0x35, 0x5b, 0xd3, 0xfb, 0x67, 0xc0, 0xa3, 0xb9, 0xeb, 0x97,
	0xfb, 0xcc, 0x3d, 0x69, 0xde, 0xeb, 0x6e, 0xde, 0x2f, 0x37, 0x1e, 0xed, 0xe5, 0xde, 0xcd, 0x6e,
	0x61, 0xf2, 0xde, 0xf9, 0xf8, 0xdb, 0x68, 0x25, 0x28, 0x6b, 0x3e, 0xb8, 0xdf, 0x1f, 0xb1, 0xfb,
	0x64, 0xce, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x69, 0x2b, 0xe9, 0x49, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GrpcClient is the client API for Grpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpcClient interface {
	SendRpcDatas(ctx context.Context, in *RpcDatas, opts ...grpc.CallOption) (*RpcReply, error)
	SendPodInfos(ctx context.Context, in *PodInfos, opts ...grpc.CallOption) (*PodReply, error)
}

type grpcClient struct {
	cc *grpc.ClientConn
}

func NewGrpcClient(cc *grpc.ClientConn) GrpcClient {
	return &grpcClient{cc}
}

func (c *grpcClient) SendRpcDatas(ctx context.Context, in *RpcDatas, opts ...grpc.CallOption) (*RpcReply, error) {
	out := new(RpcReply)
	err := c.cc.Invoke(ctx, "/kindling.Grpc/SendRpcDatas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcClient) SendPodInfos(ctx context.Context, in *PodInfos, opts ...grpc.CallOption) (*PodReply, error) {
	out := new(PodReply)
	err := c.cc.Invoke(ctx, "/kindling.Grpc/SendPodInfos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcServer is the server API for Grpc service.
type GrpcServer interface {
	SendRpcDatas(context.Context, *RpcDatas) (*RpcReply, error)
	SendPodInfos(context.Context, *PodInfos) (*PodReply, error)
}

// UnimplementedGrpcServer can be embedded to have forward compatible implementations.
type UnimplementedGrpcServer struct {
}

func (*UnimplementedGrpcServer) SendRpcDatas(ctx context.Context, req *RpcDatas) (*RpcReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRpcDatas not implemented")
}
func (*UnimplementedGrpcServer) SendPodInfos(ctx context.Context, req *PodInfos) (*PodReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPodInfos not implemented")
}

func RegisterGrpcServer(s *grpc.Server, srv GrpcServer) {
	s.RegisterService(&_Grpc_serviceDesc, srv)
}

func _Grpc_SendRpcDatas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcDatas)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServer).SendRpcDatas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kindling.Grpc/SendRpcDatas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServer).SendRpcDatas(ctx, req.(*RpcDatas))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpc_SendPodInfos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PodInfos)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServer).SendPodInfos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kindling.Grpc/SendPodInfos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServer).SendPodInfos(ctx, req.(*PodInfos))
	}
	return interceptor(ctx, in, info, handler)
}

var _Grpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kindling.Grpc",
	HandlerType: (*GrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendRpcDatas",
			Handler:    _Grpc_SendRpcDatas_Handler,
		},
		{
			MethodName: "SendPodInfos",
			Handler:    _Grpc_SendPodInfos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kindling_grpc.proto",
}
